
/*
	Given a long vector of strings, print the strings that contain the strings generated by numeric string str.
	
	string searchin [] = {
	            "prateek", "sneha", "deepak", "arnav", "shikha", "palak",
	            "utkarsh", "divyam", "nidhi", "sparsh", "akku"
	    };
	For example, if the input is 26 and the string is coding, then output should be coding since 26 can produce co which is contained in coding.
	
	Input Format
	A numeric string str
	
	Constraints
		len(str) < 10
		No of strings in the vector < 10
	
	Output Format
		Each matched string from the given vector.
	
	Sample Input:-
		34
		
	Sample Output
		
		vidhi
		divyam
		sneha
	
	Explanation:-
	34 will result into combinations :
	
	dg             eg          fg
	dh             eh          fh
	di             ei          fi
	Corresponding strings are output.
	
	1.  nidhi contains dh
	2.  divyam contains di
	3.  sneha contains eh

*/


#include<iostream>
using namespace std;
#include<algorithm>
#define ll long long
string s1[]={"","","abc","def","ghi","jkl","mno","pqrs","tuv","wxyz"};
string srch [] = {"prateek", "sneha", "deepak", "arnav", "shikha", "palak","utkarsh", "divyam", "nidhi", "sparsh", "akku"};
char out[100000];
void keypad(string s,ll int i,ll int j,ll int n)
{
	if(i==n)
	{
		out[j]='\0';
		for(int i=0;i<=10;i++)
		{
			if(srch[i].find(out)!=-1)
			cout<<srch[i]<<endl;
		}
		return;
	}
	int d=s[i]-'0';
	if(d==0|d==1)
	{
		keypad(s,i+1,j,n);
	}
	else 
	for(ll int k=0;k<s1[d].length();k++)
	{
		out[j]=s1[d][k];
		keypad(s,i+1,j+1,n);
	}
}
int main()
{
		string s;
		cin>>s;
		keypad(s,0,0,s.length());
	
}
